### ISSUE TITLE
OUT OF MEMORY ERROR!!

### ISSUE THREAD

**Issue by hemangjethava** [neural-nuts/image-caption-generator#20]
# I've tried to increase heap size for JVM but it didn't make any difference, still getting the same error. 

01-11 19:30:21.051 29425-29432/? E/art: Failed sending reply to debugger: Broken pipe
01-11 19:30:21.225 29425-29425/? W/art: Throwing OutOfMemoryError "Failed to allocate a 198571917 byte allocation with 3779736 free bytes and 186MB until OOM"
01-11 19:30:21.284 29425-29425/? W/art: Throwing OutOfMemoryError "Failed to allocate a 198571917 byte allocation with 3781696 free bytes and 186MB until OOM"
01-11 19:30:21.342 29425-29425/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.android.camera2basic, PID: 29425
                                                   java.lang.OutOfMemoryError: Failed to allocate a 198571917 byte allocation with 3781696 free bytes and 186MB until OOM
                                                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.load(TensorFlowInferenceInterface.java:401)
                                                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.initializeTensorFlow(TensorFlowInferenceInterface.java:95)
                                                       at com.example.android.camera2basic.Camera2BasicFragment.InitSession(Camera2BasicFragment.java:834)
                                                       at com.example.android.camera2basic.Camera2BasicFragment.onViewCreated(Camera2BasicFragment.java:808)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1010)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                       at android.app.BackStackRecord.run(BackStackRecord.java:815)
                                                       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1580)
                                                       at android.app.FragmentController.execPendingActions(FragmentController.java:371)
                                                       at android.app.Activity.performStart(Activity.java:6688)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by pranay360** [comment]
are you using the inbuilt android studio emulator?

**Comment by hemangjethava** [comment]
I'm using Motorola G5 plus Android phone! Haven't tried on inbuilt Android studio emulator.

**Comment by pranay360** [comment]
How much free space is available on your device?

**Comment by hemangjethava** [comment]
Around 5gb!

**Comment by hemangjethava** [comment]
Error solved hence closing this issue! 
just needed to add **android:largeHeap="true"** in **application** tag of **AndroidManifest.xml**
