### ISSUE TITLE
ValueError: cannot reshape array

### ISSUE THREAD

**Issue by Gen08** [neural-nuts/image-caption-generator#22]
How do I fix this error?
![capture](https://user-images.githubusercontent.com/37790721/37891038-633c17de-30f0-11e8-83e6-543acb4d75bb.JPG)

**Comment by metalaman** [comment]
Can you print the shape of `batch` before `batch.reshape(...)`

**Comment by AnwarUllahKhan** [comment]
I am facing the same problem how can we solve that? @metalaman 

@Gen08 can you solved the problem?

**Comment by dust0x** [comment]
@AnwarUllahKhan can you also show us the result of the `print(batch)` before line 49: `batch.reshape`?

**Comment by AnwarUllahKhan** [comment]
@dust0x same result after print(batch).   

Traceback (most recent call last):
  File "convfeatures.py", line 123, in <module>
    forward_pass(io, args.data_path)
  File "convfeatures.py", line 63, in forward_pass
    batch = batch_iter.__next__()
  File "convfeatures.py", line 50, in load_next_batch
    batch = batch.reshape(batch_size, 299, 299, 3)
ValueError: cannot reshape array of size 1 into shape (10,299,299,3)

**Comment by dust0x** [comment]
@AnwarUllahKhan I will need to see the full traceback, can you please edit to show the full traceback?

**Comment by AnwarUllahKhan** [comment]
And one error is like this.

Traceback (most recent call last):
  File "convfeatures.py", line 123, in <module>
    forward_pass(io, args.data_path)
  File "convfeatures.py", line 63, in forward_pass
    batch = batch_iter.next()
AttributeError: 'generator' object has no attribute 'next'

**Comment by AnwarUllahKhan** [comment]
I tried several time, renew everything again but still I am facing the problems see the code as well as the problem and give me some suggestion, I shall be very thankful to you.

def load_next_batch(sess, io, img_path):
    for batch_idx in range(0, len(files), batch_size):
        batch = files[batch_idx:batch_idx + batch_size]
        batch = np.array(
            map(lambda x: load_image(sess, io, img_path + x), batch))
        print(batch)
        batch = batch.reshape(batch_size, 299, 299, 3)
        yield batch

def forward_pass(io, img_path):
    global output_layer, files
    files = sorted(np.array(os.listdir(img_path)))
    print ("#Images:", len(files))
    n_batch = len(files) / batch_size
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        sess.run(init)
        batch_iter = load_next_batch(sess, io, img_path)
        for i in range(int(n_batch)):
            batch = batch_iter.__next__()
            assert batch.shape == (batch_size, 299, 299, 3)
            feed_dict = {input_layer: batch}
            if i is 0:
                prob = sess.run(
                    output_layer, feed_dict=feed_dict).reshape(
                    batch_size, 1536)
            else:
                prob = np.append(
                    prob,
                    sess.run(
                        output_layer,
                        feed_dict=feed_dict).reshape(
                        batch_size,
                        1536),
                    axis=0)
            if i % 5 == 0:

H:\First Neural Network\image-caption-generator-master>python convfeatures.py --data_path Dataset/flickr30k-images --inception_path ConvNets/inception_v4.pb
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Extracting Features
#Images: 31785
2018-08-14 16:08:54.446409: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-08-14 16:08:54.954890: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties:
name: GeForce 940MX major: 5 minor: 0 memoryClockRate(GHz): 1.2415
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.36GiB
2018-08-14 16:08:54.959630: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2018-08-14 16:08:55.667978: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-14 16:08:55.670843: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0
2018-08-14 16:08:55.672413: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N
2018-08-14 16:08:55.674010: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3086 MB memory) -> physical GPU (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0, compute capability: 5.0)
<map object at 0x0000025B163FE908>
Traceback (most recent call last):
  File "convfeatures.py", line 123, in <module>
    forward_pass(io, args.data_path)
  File "convfeatures.py", line 63, in forward_pass
    batch = batch_iter.__next__()
  File "convfeatures.py", line 50, in load_next_batch
    batch = batch.reshape(batch_size, 299, 299, 3)
ValueError: cannot reshape array of size 1 into shape (10,299,299,3)

**Comment by dust0x** [comment]
@AnwarUllahKhan: The AttributeError is thrown because of a Python version mismatch. You are most likely running Python 3.x while our code only supports Python 2.x.

What Python version are you running?

**Comment by AnwarUllahKhan** [comment]
@dust0x  I am using python 3.5 version....maybe that's why my code is not running well.

thank you very much.

**Comment by Joyce920hope** [comment]
It doesn't work.
