### ISSUE TITLE
 convfeatures.py

### ISSUE THREAD

**Issue by divyamsingh234** [neural-nuts/image-caption-generator#23]
Running This
 python convfeatures.py --data_path Dataset/flickr30k-images --inception_path ConvNets/inception_v4.pb
Gives Me this error:

2018-03-30 11:07:53.797738: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: Dataset/flickr30k-images1000092795.jpg; No such file or directory
Traceback (most recent call last):
  File "convfeatures.py", line 122, in <module>
    forward_pass(io, args.data_path)
  File "convfeatures.py", line 62, in forward_pass
    batch = batch_iter.next()
  File "convfeatures.py", line 48, in load_next_batch
    map(lambda x: load_image(sess, io, img_path + x), batch))
  File "convfeatures.py", line 48, in <lambda>
    map(lambda x: load_image(sess, io, img_path + x), batch))
  File "convfeatures.py", line 41, in load_image
    return sess.run(io[1], feed_dict={io[0]: image})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Dataset/flickr30k-images1000092795.jpg; No such file or directory
         [[Node: ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_InputFile_0_0)]]

Caused by op u'ReadFile', defined at:
  File "convfeatures.py", line 121, in <module>
    io = build_prepro_graph(args.inception_path)
  File "convfeatures.py", line 24, in build_prepro_graph
    image_file = tf.read_file(input_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 527, in read_file
    "ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Dataset/flickr30k-images1000092795.jpg; No such file or directory
         [[Node: ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_InputFile_0_0)]]

I Have included all flickr 30k images in  flickr30k-images directory

**Comment by dljzx** [comment]
same problem.How did you solve that?
