### ISSUE TITLE
__future__ imports for Python 3 compatibilty

### ISSUE THREAD

**Issue by dust0x** [neural-nuts/image-caption-generator#27]
- Python 3 style division to resolve bug in #24.
- Other \_\_future\_\_ imports for Python 3 compatibility.

Finally, this could also break intended behaviour in some places so:

- Test for forward and backward compatibility.

**Comment by jishan900** [comment]
python main.py --mode train
Required Files not present. Regenerating Data.
Loading Caption Data Dataset/results_20130124.token
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    config.word_threshold, config.max_len, caption_file, feature_file)
  File "/home/jishan/Desktop/project/utils/data_util.py", line 116, in generate_captions
    captions = [caps.replace('\n', '').split('\t')[1] for caps in data]
IndexError: list index out of range
I faced this problem right now. I used bangla dataset but unfortunate got this problem. Please help me. Thanks.
I

**Comment by dust0x** [comment]
@jishan900: Any discussions in this thread should be limited to the title, and this is not a related issue. We'd be happy to help but you must please open a new issue.
