### ISSUE TITLE
ValueError: Can not reshape array:

### ISSUE THREAD

**Issue by AnwarUllahKhan** [neural-nuts/image-caption-generator#30]
Traceback (most recent call last):
  File "convfeatures.py", line 122, in <module>
    forward_pass(io, args.data_path)
  File "convfeatures.py", line 62, in forward_pass
    batch = batch_iter.__next__()
  File "convfeatures.py", line 49, in load_next_batch
    batch = batch.reshape(batch_size, 299, 299, 3)
ValueError: cannot reshape array of size 1 into shape (10,299,299,3)

**Comment by dust0x** [comment]
Thread continued in #22.
