### ISSUE TITLE
KeyError in Serve-DualProtoBuf.py

### ISSUE THREAD

**Issue by suryawanshishantanu6** [neural-nuts/image-caption-generator#33]
I am getting this error while running Serve-DualProtoBuf.py

```
C:\E\Ai\story image\image-caption-generator>python utils\Serve-DualProtoBuf.py
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From utils\Serve-DualProtoBuf.py:26: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.
2018-09-29 22:55:00.913076: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "utils\Serve-DualProtoBuf.py", line 55, in <module>
    features = encoder_forward_pass(sess, "s2.jpg")
  File "utils\Serve-DualProtoBuf.py", line 35, in encoder_forward_pass
    in1 = graph.get_tensor_by_name("encoder/InputImage:0")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3766, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3590, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3632, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'encoder/InputImage:0' refers to a Tensor which does not exist. The operation, 'encoder/InputImage', does not exist in the graph."

```

**Comment by dust0x** [comment]
Can you print the list of tensors in encoder graph? They should be in the list object `tensors_encoder`.

**Comment by suryawanshishantanu6** [comment]
> Can you print the list of tensors in encoder graph? They should be in the list object `tensors_encoder`.

**Comment by dust0x** [comment]
Google's new [Conceptual Captions](https://github.com/google-research-datasets/conceptual-captions) dataset is worth exploring.

We trained for 50 epochs and the captions were pretty decent. But we had a resource constraint and would've liked to test how the captions improved/degraded with more epochs.
